_target_: src.models.greece_fire_models.ViT_fire_model

dynamic_features: ${sel_dynamic_features}
static_features: ${sel_static_features}
hidden_size: 32
positive_weight: 0.7
lr: 3e-4
lr_scheduler_step: 15
lr_scheduler_gamma: 0.1
weight_decay: 0.01
